owner: Hokutosei # GitHub username
repo: HexaUptime # GitHub repository name
sites: # List of endpoints to track
  - name: Hexabase Staging Login
    url: https://az.hexabase.com/login
  - name: Hexabase Staging API
    url: https://az-api.hexabase.com/health_check
  - name: Community Site
    url: https://community.hexabase.com
status-website:
  baseUrl: /HexaUptime # where "repo" is your repository name
  name: HexaUptime (trial)
