owner: Hokutosei # GitHub username
repo: HexaUptime # GitHub repository name
sites: # List of endpoints to track
  - name: Hexabase Staging Login
    url: https://az.hexabase.com/login
  - name: Hexabase Staging API
    url: https://az-api.hexabase.com/health_check
  - name: Community Site
    url: https://community.hexabase.com
  - name: Apicore Service
    url: https://az-hxg.hexabase.com/apicore/health_check
    method: GET
  - name: LinkerAPI Service
    url: https://az-hxg.hexabase.com/linkerapi/health_check
    method: GET    
assignees: # Users to assign downtime issues (optional)
  - Hokutosei
status-website:
  baseUrl: /HexaUptime # where "repo" is your repository name
  name: HexaUptime Staging Environment (trial)
commitMessages:
#   readmeContent: ":pencil: Update summary in README [skip ci] [upptime]"
#   summaryJson: ":card_file_box: Update status summary [skip ci] [upptime]"
#   statusChange: "$EMOJI $SITE_NAME is $STATUS ($RESPONSE_CODE in $RESPONSE_TIME ms) [skip ci] [upptime]"
#   graphsUpdate: ":bento: Update graphs [skip ci] [upptime]"
